name: cbirm_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  #Data
  json_annotation: ^4.8.0
  #Dependency Management
  bdaya_flutter_common: ^5.0.0
  injectable: ^2.1.0
  get_it: ^7.2.0
  #Ext
  async: ^2.9.0
  collection: ^1.17.0
  rxdart: ^0.27.7
  #Forms
  reactive_forms: ^14.3.0
  reactive_forms_annotations: ^1.1.0
  #UI
  cupertino_icons: ^1.0.2
  flutter_adaptive_scaffold: ^0.1.0
  scroll_snap_list: ^0.9.1
  smooth_page_indicator: ^1.0.1
  url_launcher: ^6.1.7
  #Backend
  blcirm_api:
    path: api
  dio: ^5.1.1
  harmony_auth: ^3.0.0
  openidconnect: ^1.0.25
  built_value: ^8.4.4
  built_collection: ^5.1.1
  infinite_scroll_pagination: ^3.2.0
  meilisearch: ^0.12.0
  change_case: ^1.1.0
  adaptive_dialog: ">=1.9.0-0"
  reactive_flutter_typeahead: ^0.8.1
  go_router: ^7.0.0
  language_picker: ^0.4.3
  reactive_language_picker: ^0.0.1
  #Firebase
  # firebase_core: ^2.1.1
  # firebase_auth: ^4.1.1
  # cloud_firestore: ^4.0.4
  # firebase_ui_auth: ^1.0.4
  # firebase_ui_firestore: ^1.0.4
  # cloud_functions: ^4.0.6
  # firebase_storage: ^11.0.9
  # cloud_firestore_odm: ^1.0.0-dev.51
dependency_overrides:
  # macos_ui:
  #   git:
  #     url: https://github.com/Mayb3Nots/macos_ui.git
  #     ref: dev
  openidconnect:
    git:
      url: git@github.com:4D-Technologies/openidconnect_flutter.git
      ref: main
      path: openidconnect
  openidconnect_web:
    git:
      url: git@github.com:4D-Technologies/openidconnect_flutter.git
      ref: main
      path: openidconnect_web
  openidconnect_platform_interface:
    git:
      url: git@github.com:4D-Technologies/openidconnect_flutter.git
      ref: main
      path: openidconnect_platform_interface
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  injectable_generator: ^2.1.3
  reactive_forms_generator: ^1.0.1
  flutter_gen_runner: ^5.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/colors/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
flutter_gen:
  output: lib/generated/
  colors:
    inputs:
      - assets/colors/dark.xml
      - assets/colors/light.xml
